about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about_me, name='about'),
]

anime_review/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.AnimeList.as_view(), name="review"),
    path('<slug:slug>/', views.anime_detail, name='anime_detail'),
    path('<slug:slug>/edit_review/<int:review_id>',
         views.review_edit, name='review_edit'),
    path('<slug:slug>/delete_review/<int:review_id>',
         views.review_delete, name='review_delete'),
]

codestar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('review', include("anime_review.urls"), name="anime-review-urls"),
    path('summernote/', include('django_summernote.urls')),
    path("", include("anime_blog.urls"), name="anime-blog-urls"),
]

anime_review/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))


class Anime(models.Model):
    """
    Stores a single anime entry related to :model:`auth.User`.
    """
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="anime_reviews"
    )
    anime_cover = CloudinaryField('cover', default='placeholder')
    status = models.IntegerField(choices=STATUS, default=0)
    content = models.TextField(default='')
    created_on = models.DateTimeField(auto_now_add=True)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        Returns the string representation of the Anime object.
        """
        return self.title


class Review(models.Model):
    """
    Stores a single review entry related to :model:`auth.User`
    and :model:`anime_review.Anime`.
    """
    RATE_CHOICES = (
        (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
        (6, 6), (7, 7), (8, 8), (9, 9), (10, 10),
    )
    anime = models.ForeignKey(
        Anime, on_delete=models.CASCADE, related_name="reviews"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="reviewer"
    )
    body = models.TextField()
    approved = models.BooleanField(default=False)
    stars = models.IntegerField(choices=RATE_CHOICES)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns the string representation of the Review object.
        """
        return f"Review {self.body} by {self.author}"

anime_review/forms.py
from django import forms
from .models import Review


class AnimeReviewForm(forms.ModelForm):
    """
    Form for creating or updating anime reviews.
    """
    class Meta:
        model = Review
        fields = ["stars", "body"]

anime_review/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.views.generic import UpdateView
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Anime, Review
from .forms import AnimeReviewForm


class AnimeList(generic.ListView):
    """
    View for listing anime reviews.
    """
    queryset = Anime.objects.filter(status=1)
    template_name = "anime_review/review.html"
    paginate_by = 6


def anime_detail(request, slug):
    """
    View for displaying details of a specific anime and its reviews.

    **Context**

    ``anime``
        An instance of :model:`anime_review.Anime`.
    ``reviews``
        List of reviews related to the anime.
    ``review_count``
        Number of approved reviews for the anime.
    ``anime_review_form``
        An instance of :form:`anime_review.AnimeReviewForm`.
    """
    queryset = Anime.objects.filter(status=1)
    anime = get_object_or_404(queryset, slug=slug)
    reviews = anime.reviews.all().order_by("-created_on")
    review_count = anime.reviews.filter(approved=True).count()

    if request.method == "POST":
        anime_review_form = AnimeReviewForm(data=request.POST)
        if anime_review_form.is_valid():
            review = anime_review_form.save(commit=False)
            review.author = request.user
            review.stars = request.POST.get('stars')
            review.anime = anime
            review.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Review submitted and awaiting approval'
            )

    anime_review_form = AnimeReviewForm()

    return render(
        request,
        "anime_review/anime_detail.html",
        {
            "anime": anime,
            "reviews": reviews,
            "review_count": review_count,
            "anime_review_form": anime_review_form,
        },
    )


def review_edit(request, slug, review_id):
    """
    View for editing an individual review.

    **Context**

    ``anime``
        An instance of :model:`anime_review.Anime`.
    ``review``
        An instance of :model:`anime_review.Review`.
    ``anime_review_form``
        An instance of :form:`anime_review.AnimeReviewForm`.
    """
    if request.method == "POST":
        queryset = Anime.objects.filter(status=1)
        anime = get_object_or_404(queryset, slug=slug)
        review = get_object_or_404(Review, pk=review_id)
        anime_review_form = AnimeReviewForm(
            data=request.POST, instance=review)

        if anime_review_form.is_valid() and review.author == request.user:
            review = anime_review_form.save(commit=False)
            review.anime = anime
            review.approved = False
            review.save()
            messages.add_message(request, messages.SUCCESS, 'Review Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating review!')

    return HttpResponseRedirect(reverse('anime_detail', args=[slug]))


def review_delete(request, slug, review_id):
    """
    View for deleting an individual review.

    **Context**

    ``anime``
        An instance of :model:`anime_review.Anime`.
    ``review``
        An instance of :model:`anime_review.Review`.
    """
    queryset = Anime.objects.filter(status=1)
    anime = get_object_or_404(queryset, slug=slug)
    review = get_object_or_404(Review, pk=review_id)

    if review.author == request.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS, 'Review deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own reviews!')

    return HttpResponseRedirect(reverse('anime_detail', args=[slug]))

anime_review/templates/anime_review/anime_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}


<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Anime title goes in these h1 tags -->
                <h1 class="anime-title">{{ anime.title }}</h1>
                <!-- anime author goes before the | the anime's created date goes after -->
                <p class="post-subtitle">{{ anime.author }} | {{ anime.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                {% if "placeholder" in anime.anime_cover.url %}
                <img src="{% static 'images/anime_default.jpg' %}" class="scale" alt="placeholder image">
                {% else %}
                <img src="{{ anime.anime_cover.url }}" class="scale" alt="{{ anime.title }}">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The anime content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <article class="card-text">
                    <h3>Anime details:</h3>
                    {{ anime.content | safe }}
                </article>
            </div>
        </div>
    </div>
    <!-- Displaying count of reviews -->
    <div class="row">
        <div class="col-12">
            <strong class="text-secondary">
                <i class="far fa-comments"></i> {{ review_count }}
            </strong>
        </div>
        <div class="col-12">
            <hr>
        </div>
    </div>
    <!-- Displaying reviews -->
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Reviews:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags
          to iterate through each review in reviews -->
                {% for review in reviews %}
                <div class="p-2 comments
          {% if not review.approved and review.author == user %}
          faded{% elif not review.approved %} d-none{% endif %}">
                    <p class="font-weight-bold">
                        {{ review.author }}
                        <span class="font-weight-normal">
                            {{ review.created_on }}
                        </span> wrote:
                    </p>
                    <div id="starRatingId{{ review.id }}">
                        {{ review.stars | linebreaks }}
                    </div>
                    <div id="review{{ review.id }}">
                        {{ review.body | linebreaks }}
                    </div>
                    {% if not review.approved and review.author == user %}
                    <p class="approval">
                        This review is awaiting approval
                    </p>
                    {% endif %}
                    {% if user.is_authenticated and review.author == user %}
                    <button class="btn btn-delete" data-review_id="{{ review.id }}">Delete</button>
                    <button class="btn btn-edit" data-review_id="{{ review.id }}">Edit</button>
                    {% endif %}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <!-- Creating New Reviews -->
        <div class="col-md-4 card mb-4 mt-3">
            <div class="card-body">
                {% if user.is_authenticated %}
                <h3>Leave a review for this Anime entry:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form id="AnimeReviewForm" method="POST" style="margin-top: 1.3em;">
                    {{ anime_review_form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% else %}
                <p>Log in to leave a review</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete review?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your review?
                This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/reviews.js' %}"></script>
{% endblock %}

anime_review/templates/anime_review/review.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- review.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for anime in anime_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in anime.anime_cover.url %}
                                <img class="card-img-top" src="{% static 'images/anime_default.jpg' %}"
                                    alt="placeholder image">
                                {% else %}
                                <img class="card-img-top" src=" {{ anime.anime_cover.url }}" alt="{{ anime.title }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Contributor: {{ anime.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'anime_detail' anime.slug %}" class="post-link">
                                <h2 class="card-title">{{ anime.title }}</h2>
                                <p class="card-text">{{ anime.excerpt }}</p>
                            </a>

                            <hr/>
                            <p class="card-text text-muted h6">{{ anime.created_on}}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- review.html content ends here -->
{% endblock %}

{% block copyright %}
Copyright 2024 Andreas Charalambous
{% endblock %}